server:
  port: 8380
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: epie
  datasource:
    url: jdbc:mysql://rm-bp132k4d3i28zu7928o.mysql.rds.aliyuncs.com:3306/epie?serverTimezone=UTC
    username: epie
    password: Epie@cloud
    driver-class-name: com.mysql.cj.jdbc.Driver
