server:
  port: 8380
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.26.184.150:8761/

spring:
  application:
    name: epie
  datasource:
    url: jdbc:mysql://localhost:3306/epie?serverTimezone=UTC
    username: root
    password: 123321
    driver-class-name: com.mysql.cj.jdbc.Driver
message:
  key:
    length: 16
    package:
      number: 4